version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - markdown_data:/app/data
      - ./logs:/app/logs
    environment:
      - PROJECT_NAME=Markdown Forge
      - VERSION=1.0.0
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - DATABASE_URL=sqlite:///./data/markdown_forge.db
      - MAX_UPLOAD_SIZE=10485760  # 10MB
      - USE_PANDOC=${USE_PANDOC:-false}
      - UPLOAD_FOLDER=/app/data/uploads
      - OUTPUT_FOLDER=/app/data/output
      - LOG_FOLDER=/app/logs
      - ALLOWED_EXTENSIONS=md,markdown,mdown,mkdn
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    user: "${UID:-1000}:${GID:-1000}"  # Run as non-root user
    init: true  # Better signal handling and zombie process reaping

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=markdown_forge
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  markdown_data:
    name: markdown_forge_data
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data  # Mount from local directory 